[project]
name = 'Digital-Collectible-Card-Game'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.battle-mechanics]
path = 'contracts/battle-mechanics.clar'
clarity_version = 2
epoch = 2.5

[contracts.card-nft]
path = 'contracts/card-nft.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
